version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - chmod +x ./gradlew
      - ./gradlew build

    post_build:
      commands:
        - echo $(basename ./build/libs/*.jar)
        - pwd
artifacts:
  files:
    - libs/*.jar
  base-directory: build
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/cache/**/*'