language: java
jdk:
  - openjdk21
branches:
  only:
    - master



cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


script: "./gradlew clean build"


notifications:
  email:
    recipients:
      deer159123@naver.com